package com.ittzg.mybatis.dao;

import com.ittzg.mybatis.entity.Score;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    int insertSelective(Score record);
}