package com.ittzg.mybatis.entity;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.user_id
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.user_id
     *
     * @return the value of score.user_id
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.user_id
     *
     * @param userId the value for score.user_id
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbggenerated Fri Nov 06 15:08:22 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}